// Configurator texts, carried over from ruben-pap (assets/js/i18n.js, cfg.*). {name} marks a placeholder.
import type { Locale } from './i18n'

const en = {
  "piece": "Piece",
  "no": "No. {n}",
  "price": "Price on request",
  "unique": "Handmade in Yerevan · every piece is one of a kind",
  "size": "Size",
  "size.s": "Small",
  "size.m": "Medium",
  "size.l": "Large",
  "glaze": "Glaze",
  "g.bronze": "Bronze",
  "g.graphite": "Graphite",
  "g.turquoise": "Deep turquoise",
  "g.clay": "Natural clay",
  "g.ivory": "Ivory",
  "surface": "Surface",
  "flow": "Glaze flow",
  "tex": "Texture",
  "luster": "Sheen",
  "qty": "Quantity",
  "qtyDec": "Decrease quantity",
  "qtyInc": "Increase quantity",
  "name": "Your name",
  "note": "Note",
  "optional": "optional",
  "notePh": "e.g. a gift, a preferred date…",
  "msg": "Your message",
  "send": "Send via",
  "copy": "Copy message",
  "copyLink": "Copy link to this design",
  "copied": "Message copied.",
  "linkCopied": "Link copied.",
  "copyFail": "Couldn’t copy — please select the text and copy it.",
  "pasteHint": "Message copied — paste it into the chat.",
  "approx": "Sizes are approximate; colours are a digital preview. Every piece is thrown and fired by hand.",
  "views": "Views",
  "view3d": "View in 3D",
  "photo": "Photo {n}",
  "dims": "Show dimensions",
  "mug": "Compare with a mug",
  "reset": "Reset view",
  "full": "Full screen",
  "hint": "Drag to rotate · scroll or pinch to zoom",
  "hintTouch": "Swipe sideways to rotate · pinch to zoom",
  "loading": "Loading 3D…",
  "noWebgl": "3D preview isn’t available on this device — showing photos instead.",
  "canvas": "3D preview: {piece}, {size}, {glaze}. Use the arrow keys to rotate.",
  "h": "H",
  "w": "W",
  "cm": "cm",
  "mugLabel": "Mug · 9.5 cm",
  "m.intro": "Hello! I'd like to order a piece from the Ruben Pap Ceramics website:",
  "m.piece": "{piece} (No. {n})",
  "m.size": "Size: {size} — {dims}",
  "m.glaze": "Glaze: {glaze} (flow {flow}%, texture {tex}%, sheen {luster}%)",
  "m.qty": "Quantity: {qty}",
  "m.note": "Note: {note}",
  "m.name": "My name: {name}",
  "m.ask": "Could you tell me the price and when it could be ready?",
  "m.link": "My design: {link}",
  "m.subject": "Order request: {piece} ({size})",
  "title": "Make it yours",
  "text": "Turn each piece in 3D, compare three sizes and try other glazes. Your choices become a ready-to-send message.",
  "email": "Email",
}

export type CfgT = typeof en

export const cfgDict: Record<Locale, CfgT> = {
  en,
  hy: {
    "piece": "Աշխատանք",
    "no": "№ {n}",
    "price": "Գինը՝ ըստ հարցման",
    "unique": "Ձեռագործ՝ Երևանում · յուրաքանչյուր իր եզակի է",
    "size": "Չափս",
    "size.s": "Փոքր",
    "size.m": "Միջին",
    "size.l": "Մեծ",
    "glaze": "Ջնարակ",
    "g.bronze": "Բրոնզ",
    "g.graphite": "Գրաֆիտ",
    "g.turquoise": "Խոր փիրուզագույն",
    "g.clay": "Բնական կավ",
    "g.ivory": "Փղոսկր",
    "surface": "Մակերես",
    "flow": "Ջնարակի հոսք",
    "tex": "Ֆակտուրա",
    "luster": "Փայլ",
    "qty": "Քանակ",
    "qtyDec": "Պակասեցնել քանակը",
    "qtyInc": "Ավելացնել քանակը",
    "name": "Ձեր անունը",
    "note": "Նշում",
    "optional": "ըստ ցանկության",
    "notePh": "օրինակ՝ նվեր, նախընտրելի ամսաթիվ…",
    "msg": "Ձեր հաղորդագրությունը",
    "send": "Ուղարկել",
    "copy": "Պատճենել հաղորդագրությունը",
    "copyLink": "Պատճենել այս տարբերակի հղումը",
    "copied": "Հաղորդագրությունը պատճենված է։",
    "linkCopied": "Հղումը պատճենված է։",
    "copyFail": "Չհաջողվեց պատճենել․ ընտրեք տեքստը և պատճենեք։",
    "pasteHint": "Հաղորդագրությունը պատճենված է․ տեղադրեք այն զրույցում։",
    "approx": "Չափսերը մոտավոր են, գույները՝ թվային նախադիտում։ Յուրաքանչյուր իր պատրաստվում և թրծվում է ձեռքով։",
    "views": "Տեսքեր",
    "view3d": "Դիտել 3D-ով",
    "photo": "Լուսանկար {n}",
    "dims": "Ցույց տալ չափերը",
    "mug": "Համեմատել բաժակի հետ",
    "reset": "Վերականգնել տեսքը",
    "full": "Լիաէկրան",
    "hint": "Քաշեք՝ պտտելու համար · խոշորացրեք անիվով կամ երկու մատով",
    "hintTouch": "Սահեցրեք կողք՝ պտտելու համար · երկու մատով՝ խոշորացնելու",
    "loading": "3D-ն բեռնվում է…",
    "noWebgl": "3D նախադիտումը հասանելի չէ այս սարքում․ ցուցադրվում են լուսանկարները։",
    "canvas": "3D նախադիտում՝ {piece}, {size}, {glaze}։ Պտտելու համար օգտագործեք սլաքները։",
    "h": "Բ",
    "w": "Լ",
    "cm": "սմ",
    "mugLabel": "Բաժակ · 9,5 սմ",
    "m.intro": "Բարև Ձեզ։ Կցանկանայի պատվիրել աշխատանք Ruben Pap Ceramics կայքից․",
    "m.piece": "{piece} (№ {n})",
    "m.size": "Չափս՝ {size} — {dims}",
    "m.glaze": "Ջնարակ՝ {glaze} (հոսք {flow}%, ֆակտուրա {tex}%, փայլ {luster}%)",
    "m.qty": "Քանակ՝ {qty}",
    "m.note": "Նշում՝ {note}",
    "m.name": "Իմ անունը՝ {name}",
    "m.ask": "Կասե՞ք գինը և երբ կարող է պատրաստ լինել։",
    "m.link": "Իմ տարբերակը՝ {link}",
    "m.subject": "Պատվերի հարցում՝ {piece} ({size})",
    "title": "Ստեղծեք ձերը",
    "text": "Պտտեք յուրաքանչյուր աշխատանքը 3D-ում, համեմատեք երեք չափսերը և փորձեք այլ ջնարակներ։ Ձեր ընտրությունը կդառնա ուղարկելու պատրաստ հաղորդագրություն։",
    "email": "Էլ. փոստ",
  },
  ru: {
    "piece": "Изделие",
    "no": "№ {n}",
    "price": "Цена по запросу",
    "unique": "Ручная работа, Ереван · каждое изделие уникально",
    "size": "Размер",
    "size.s": "Маленький",
    "size.m": "Средний",
    "size.l": "Большой",
    "glaze": "Глазурь",
    "g.bronze": "Бронза",
    "g.graphite": "Графит",
    "g.turquoise": "Глубокая бирюза",
    "g.clay": "Натуральная глина",
    "g.ivory": "Слоновая кость",
    "surface": "Поверхность",
    "flow": "Потёки глазури",
    "tex": "Фактура",
    "luster": "Блеск",
    "qty": "Количество",
    "qtyDec": "Уменьшить количество",
    "qtyInc": "Увеличить количество",
    "name": "Ваше имя",
    "note": "Комментарий",
    "optional": "необязательно",
    "notePh": "например, подарок, желаемая дата…",
    "msg": "Ваше сообщение",
    "send": "Отправить через",
    "copy": "Скопировать сообщение",
    "copyLink": "Скопировать ссылку на вариант",
    "copied": "Сообщение скопировано.",
    "linkCopied": "Ссылка скопирована.",
    "copyFail": "Не удалось скопировать — выделите текст и скопируйте вручную.",
    "pasteHint": "Сообщение скопировано — вставьте его в чат.",
    "approx": "Размеры приблизительные, цвета — цифровое превью. Каждое изделие формуется и обжигается вручную.",
    "views": "Ракурсы",
    "view3d": "Смотреть в 3D",
    "photo": "Фото {n}",
    "dims": "Показать размеры",
    "mug": "Сравнить с кружкой",
    "reset": "Сбросить вид",
    "full": "Во весь экран",
    "hint": "Тяните, чтобы вращать · колесо или щипок — масштаб",
    "hintTouch": "Проведите вбок, чтобы вращать · щипок — масштаб",
    "loading": "Загрузка 3D…",
    "noWebgl": "3D-просмотр недоступен на этом устройстве — показаны фото.",
    "canvas": "3D-просмотр: {piece}, {size}, {glaze}. Вращайте стрелками.",
    "h": "В",
    "w": "Ш",
    "cm": "см",
    "mugLabel": "Кружка · 9,5 см",
    "m.intro": "Здравствуйте! Хочу заказать изделие с сайта Ruben Pap Ceramics:",
    "m.piece": "{piece} (№ {n})",
    "m.size": "Размер: {size} — {dims}",
    "m.glaze": "Глазурь: {glaze} (потёки {flow}%, фактура {tex}%, блеск {luster}%)",
    "m.qty": "Количество: {qty}",
    "m.note": "Комментарий: {note}",
    "m.name": "Меня зовут {name}.",
    "m.ask": "Подскажите, пожалуйста, цену и сроки изготовления.",
    "m.link": "Мой вариант: {link}",
    "m.subject": "Заказ: {piece} ({size})",
    "title": "Сделайте по-своему",
    "text": "Вращайте изделие в 3D, сравнивайте три размера и примеряйте другие глазури. Ваш выбор превратится в готовое к отправке сообщение.",
    "email": "Эл. почта",
  },
  de: {
    "piece": "Stück",
    "no": "Nr. {n}",
    "price": "Preis auf Anfrage",
    "unique": "Handgemacht in Jerewan · jedes Stück ein Unikat",
    "size": "Größe",
    "size.s": "Klein",
    "size.m": "Mittel",
    "size.l": "Groß",
    "glaze": "Glasur",
    "g.bronze": "Bronze",
    "g.graphite": "Graphit",
    "g.turquoise": "Tiefes Türkis",
    "g.clay": "Naturton",
    "g.ivory": "Elfenbein",
    "surface": "Oberfläche",
    "flow": "Glasurfluss",
    "tex": "Struktur",
    "luster": "Glanz",
    "qty": "Anzahl",
    "qtyDec": "Anzahl verringern",
    "qtyInc": "Anzahl erhöhen",
    "name": "Ihr Name",
    "note": "Anmerkung",
    "optional": "optional",
    "notePh": "z. B. ein Geschenk, Wunschtermin …",
    "msg": "Ihre Nachricht",
    "send": "Senden über",
    "copy": "Nachricht kopieren",
    "copyLink": "Link zu diesem Entwurf kopieren",
    "copied": "Nachricht kopiert.",
    "linkCopied": "Link kopiert.",
    "copyFail": "Kopieren nicht möglich — bitte Text markieren und kopieren.",
    "pasteHint": "Nachricht kopiert — fügen Sie sie im Chat ein.",
    "approx": "Maße sind Richtwerte, Farben eine digitale Vorschau. Jedes Stück wird von Hand gedreht und gebrannt.",
    "views": "Ansichten",
    "view3d": "In 3D ansehen",
    "photo": "Foto {n}",
    "dims": "Maße anzeigen",
    "mug": "Mit einer Tasse vergleichen",
    "reset": "Ansicht zurücksetzen",
    "full": "Vollbild",
    "hint": "Ziehen zum Drehen · Scrollen oder zwei Finger zum Zoomen",
    "hintTouch": "Seitlich wischen zum Drehen · zwei Finger zum Zoomen",
    "loading": "3D wird geladen …",
    "noWebgl": "3D-Vorschau ist auf diesem Gerät nicht verfügbar — stattdessen Fotos.",
    "canvas": "3D-Vorschau: {piece}, {size}, {glaze}. Mit den Pfeiltasten drehen.",
    "h": "H",
    "w": "B",
    "cm": "cm",
    "mugLabel": "Tasse · 9,5 cm",
    "m.intro": "Hallo! Ich möchte ein Stück von der Website von Ruben Pap Ceramics bestellen:",
    "m.piece": "{piece} (Nr. {n})",
    "m.size": "Größe: {size} — {dims}",
    "m.glaze": "Glasur: {glaze} (Fluss {flow} %, Struktur {tex} %, Glanz {luster} %)",
    "m.qty": "Anzahl: {qty}",
    "m.note": "Anmerkung: {note}",
    "m.name": "Mein Name: {name}",
    "m.ask": "Können Sie mir den Preis und die Fertigungszeit nennen?",
    "m.link": "Mein Entwurf: {link}",
    "m.subject": "Bestellanfrage: {piece} ({size})",
    "title": "Ganz nach Ihrem Geschmack",
    "text": "Drehen Sie jedes Stück in 3D, vergleichen Sie drei Größen und probieren Sie andere Glasuren. Ihre Auswahl wird zu einer versandfertigen Nachricht.",
    "email": "E-Mail",
  },
}

/** Fills {name} placeholders. */
export const fill = (s: string, vars: Record<string, string | number>) => s.replace(/\{(\w+)\}/g, (m, k: string) => String(vars[k] ?? m))
