import type { Locale } from './i18n'

/** English is the source of truth; other languages override it section by section. */
const en = {
  meta: {
    title: 'Ruben Pap Ceramics',
    description:
      'Ceramic artist Ruben Pap makes tableware for restaurants, objects for collectors and tiles for architecture — by hand, in Yerevan, since 2012.',
  },
  ui: { skip: 'Skip to content', menu: 'Menu', main: 'Main', language: 'Language', cart: 'Cart', theme: 'Light / dark', back: 'Home', prev: 'Previous', next: 'Next' },
  brand: { sub: 'Ceramics · Yerevan' },
  nav: {
    restaurants: 'Restaurants & Tableware',
    art: 'Original Art',
    tiles: 'Decor & Tiles',
    shop: 'Shop',
    about: 'About',
    contact: 'Contact',
  },
  home: {
    titleThin: 'Made by hand.',
    titleBold: 'Made with character.',
    meta1: 'Ceramics — handmade, made to order',
    meta2: 'Est. 2012 · Yerevan',
    worldsTitle: 'Four worlds',
    worldsCount: '4 directions',
    commissionLink: 'Commission',
    worksTitle: 'Selected works',
    partners: 'Restaurant partners',
    studio: 'From the studio',
    title: 'Made by hand. Made with character.',
    text: 'Ceramic artist Ruben Pap makes tableware for restaurants, objects for collectors and tiles for architecture — in his Yerevan studio since 2012.',
    alt: 'Pierced stoneware bowl against a studio window',
    restaurants: 'Custom ceramic tableware for hospitality.',
    art: 'Imaginative ceramic objects and collectible works.',
    tiles: 'Handmade surfaces and decor for interiors and architectural spaces.',
    shop: 'Available pieces made in the studio.',
    explore: 'Explore',
    shopNow: 'Shop now',
    selected: 'Selected objects',
    all: 'All works',
  },
  band: {
    title: 'Have a project in mind?',
    text: 'Tell us about it — Ruben replies personally.',
    restaurant: 'Restaurant',
    art: 'Art piece',
    tiles: 'Tiles',
  },
  restaurants: {
    makeSub: '06 types · choose and order',
    order: 'Order',
    oursTitle: 'Our restaurants',
    oursSub: 'Projects Ruben made tableware for',
    keepTitle: 'Keep exploring…',
    keepSub: 'The other directions',
    forYou: 'For your restaurant',
    title: 'Tableware made for your menu.',
    text: 'A ceramic collection designed around your food, your room and your service — from first sketch to reorder.',
    cta: 'Order a Custom Collection',
    cta2: 'Discuss Your Restaurant Project',
    makeTitle: 'What we make',
    make: ['Plates', 'Bowls', 'Cups & mugs', 'Serving dishes', 'Specialty tableware', 'Custom shapes & sizes'],
    customTitle: 'What you can customise',
    custom: ['Shape & size', 'Glaze & colour development', 'Surface & rim', 'Your mark stamped underneath', 'Set composition'],
    serviceTitle: 'Built for service',
    service: 'Ask for the specs that matter in a kitchen: stacking, dishwasher use, rim strength, food-safe glazes.',
    projectsTitle: 'Projects',
    projectsEmpty: 'Case studies are being photographed. Write to us for references.',
    stepsTitle: 'How it works',
    steps: ['Brief', 'Samples', 'Prototype set', 'Approval', 'Production', 'Delivery & reorders'],
  },
  art: {
    worksBand: 'Works',
    title: 'Clay, fire & the unknown.',
    text: 'Sculptural vessels and one-of-a-kind works — thrown on the wheel, then cut, folded and pierced by hand.',
    cta: 'Commission a Piece',
    commissionTitle: 'A piece for your space.',
    commissionText: 'Start from an existing work or from a blank page.',
    year: 'Year',
    material: 'Material',
    dimensions: 'Dimensions',
    collection: 'Collection',
    available: 'Available in the shop',
    similar: 'Commission a similar piece',
    all: 'All',
    more: 'More works',
    startFrom: 'Start from an existing work',
    empty: 'New works are on their way.',
    cats: {
      sculptural: 'Sculptural',
      vases: 'Vases',
      objects: 'Decorative objects',
      interior: 'Interior objects',
      experimental: 'Experimental',
      limited: 'Limited collections',
    },
  },
  tiles: {
    title: 'Surfaces made by hand, for spaces made to last.',
    text: 'Bespoke ceramic tiles for architects, designers and the spaces they build — any shape, glaze or pattern.',
    cta: 'Request Custom Tiles',
    cta2: 'Start a Tile Project',
    forTitle: 'Made for',
    for: ['Architects', 'Interior designers', 'Restaurants & hotels', 'Homes', 'Commercial spaces'],
    customTitle: 'Custom development',
    custom: ['Dimensions', 'Shapes', 'Patterns', 'Glaze variations', 'Textures', 'Bespoke development'],
    stepsTitle: 'How it works',
    steps: ['Brief', 'Sample box', 'Mock-up panel', 'Production', 'Delivery'],
    projectsTitle: 'Projects',
    projectsEmpty: 'Installations are being photographed. Write to us for references.',
  },
  project: {
    partner: 'Partner restaurant',
    viewWorks: 'View the works',
    and: 'and',
    served: 'Ceramic tableware made for the restaurant’s kitchen, room and service.',
    glance: 'The restaurant at a glance',
    worksTitle: 'Works for the restaurant',
    worksSub: '{n} works · tableware and serving pieces',
    cardText: 'Handmade at the Ruben Pap studio, Yerevan.',
    orderSimilar: 'Order similar',
    howWorked: 'How we worked',
    similarTitle: 'Order a similar collection',
    similarText: 'Tell us about your menu and your room — Ruben replies personally.',
    all: 'All restaurants',
    others: 'Other restaurants Ruben worked with',
    closed: 'Closed',
    concept: 'Concept',
    collection: 'Collection',
    materials: 'Materials & glazes',
    tile: 'Tile',
    pattern: 'Pattern',
    start: 'Start your project',
  },
  shop: {
    title: 'Available now.',
    text: 'Made in the studio, ready to ship. When a one-of-a-kind piece sells, it’s gone.',
    all: 'All',
    cats: {
      cups: 'Cups',
      mugs: 'Mugs',
      plates: 'Plates',
      bowls: 'Bowls',
      vases: 'Vases',
      decor: 'Decor',
      limited: 'Limited Editions',
      unique: 'One-of-a-Kind',
    },
    empty: 'Nothing here right now — new pieces are on their way from the kiln.',
    customTitle: 'Want something made especially for you?',
    customText: 'Describe it, add a few reference photos — Ruben will make it.',
    customCta: 'Request a Custom Piece',
    variant: 'Love it, but in another size or glaze?',
    onRequest: 'Price on request',
    unique: 'One of a kind',
    soldOut: 'Sold out',
    add: 'Add to cart',
    added: 'In your cart — view',
    ask: 'Ask about this piece',
    handmade: 'Thrown and glazed by hand in Yerevan. Small differences in form and glaze are the maker’s mark, not flaws.',
    material: 'Material',
    glaze: 'Glaze',
    dimensions: 'Dimensions',
    care: 'Care',
    story: 'About the work',
  },
  cart: {
    title: 'Cart',
    empty: 'Nothing here yet. The kiln is always full, though.',
    qty: 'Quantity',
    remove: 'Remove',
    total: 'Total',
    send: 'Send order by email',
    note: 'Online payment is coming soon. Send the order and we’ll confirm availability and shipping.',
    back: 'Continue shopping',
    subject: 'Order from the website',
  },
  form: {
    title: 'Start a project',
    text: 'Tell us what you’re planning. Only fields marked * are required.',
    type: 'Project type *',
    types: { restaurant: 'Restaurant collection', art: 'Art piece', tiles: 'Tiles', custom: 'Custom piece' },
    ref: 'Reference',
    venue: 'Venue name',
    city: 'City',
    pieces: 'Pieces needed',
    piecesList: { plates: 'Plates', bowls: 'Bowls', cups: 'Cups & mugs', serving: 'Serving dishes', specialty: 'Specialty' },
    quantity: 'Quantity',
    kind: 'Type of work',
    kinds: { sculpture: 'Sculpture', vase: 'Vase', object: 'Object', installation: 'Installation' },
    size: 'Approximate size (cm)',
    placement: 'Where will it live?',
    role: 'Your role',
    roles: { architect: 'Architect', designer: 'Interior designer', owner: 'Owner', contractor: 'Contractor' },
    area: 'Area (m²)',
    application: 'Application',
    applications: { wall: 'Wall', floor: 'Floor', backsplash: 'Backsplash', facade: 'Facade', wet: 'Wet area' },
    item: 'What should we make?',
    brief: 'Describe your project *',
    budget: 'Budget',
    budgets: ['Not sure yet', 'Under $500', '$500 – 2,000', '$2,000 – 10,000', 'Over $10,000'],
    deadline: 'Deadline',
    files: 'Reference images or drawings',
    filesHint: 'Up to 10 files, 4 MB in total.',
    tooBig: 'The files are larger than 4 MB in total.',
    you: 'About you',
    name: 'Name *',
    email: 'Email',
    phone: 'Phone / WhatsApp',
    contactHint: 'Email or phone is required.',
    channel: 'Preferred channel',
    channels: ['Email', 'WhatsApp', 'Telegram', 'Viber', 'Phone call'],
    send: 'Send',
    sending: 'Sending…',
    sent: 'Thank you — your brief is with Ruben. He replies personally.',
    failed: 'We couldn’t send the form online. Email the same brief instead:',
    mail: 'Open email',
  },
  about: {
    label: 'About the artist',
    name: 'Ruben Pap',
    p1: 'Ruben began learning ceramics at 22, working in a Yerevan studio and spending a decade experimenting with form, clay and glaze.',
    p2: 'In 2012 he opened his own studio. His practice moves freely between art, design and functional ware — combining traditional wheel-throwing with cutting and altering that gives each piece a linear, living structure.',
    p3: 'Layered glazes over warm brown clay are his signature, from deep turquoise to the bronze surfaces of his newest work.',
    quote: '“When I am making a piece, I never know what is going to happen.”',
    f1: 'Age he started',
    f2: 'Studio founded',
    alt: 'Ruben Pap at work in his studio',
  },
  contact: {
    title: 'Say hello.',
    email: 'Email',
    phone: 'Phone',
    studio: 'Studio',
    follow: 'Follow',
    address: 'Komitas St. 49/3, 14, Yerevan, Armenia',
    visits: 'Studio visits by appointment',
    map: 'Map',
  },
  footer: {
    contact: 'Contact',
    studio: 'Studio',
    social: 'Social',
    tagline: 'By hand · Clay · Fire',
  },
  notFound: { title: 'This page cracked in the kiln.', back: 'Back home' },
}

export type Dict = typeof en
type Overrides = { [K in keyof Dict]?: Partial<Dict[K]> }

const hy: Overrides = {
  meta: {
    description:
      'Կերամիկայի վարպետ Ռուբեն Պապը ստեղծում է սպասք ռեստորանների, առարկաներ կոլեկցիոներների և սալիկներ ճարտարապետության համար՝ ձեռքով, Երևանում, 2012 թվականից։',
  },
  ui: { skip: 'Անցնել բովանդակությանը', menu: 'Մենյու', main: 'Հիմնական', language: 'Լեզու', cart: 'Զամբյուղ', theme: 'Լուսավոր / մութ', back: 'Գլխավոր', prev: 'Նախորդ', next: 'Հաջորդ' },
  brand: { sub: 'Կերամիկա · Երևան' },
  nav: {
    restaurants: 'Ռեստորաններ և սպասք',
    art: 'Հեղինակային արվեստ',
    tiles: 'Դեկոր և սալիկներ',
    shop: 'Խանութ',
    about: 'Վարպետը',
    contact: 'Կապ',
  },
  home: {
    titleThin: 'Ձեռքով ստեղծված։',
    titleBold: 'Բնավորությամբ օժտված։',
    meta1: 'Կերամիկա — ձեռագործ, պատվերով',
    meta2: 'Հիմն. 2012 · Երևան',
    worldsTitle: 'Չորս աշխարհ',
    worldsCount: '4 ուղղություն',
    commissionLink: 'Պատվիրել',
    worksTitle: 'Ընտրված աշխատանքներ',
    partners: 'Ռեստորան-գործընկերներ',
    studio: 'Արվեստանոցից',
    title: 'Ստեղծված ձեռքով։ Ստեղծված բնավորությամբ։',
    text: 'Կերամիկայի վարպետ Ռուբեն Պապը ստեղծում է սպասք ռեստորանների, առարկաներ կոլեկցիոներների և սալիկներ ճարտարապետության համար՝ իր երևանյան արվեստանոցում, 2012 թվականից։',
    alt: 'Ծակոտկեն կավե թաս արվեստանոցի պատուհանի ֆոնին',
    restaurants: 'Անհատական կերամիկական սպասք հյուրընկալության ոլորտի համար։',
    art: 'Երևակայությամբ լի կերամիկական առարկաներ և հավաքածուային աշխատանքներ։',
    tiles: 'Ձեռագործ մակերեսներ և դեկոր ինտերիերի ու ճարտարապետական տարածքների համար։',
    shop: 'Արվեստանոցում պատրաստված, առկա աշխատանքներ։',
    explore: 'Դիտել',
    shopNow: 'Գնել',
    selected: 'Ընտրված առարկաներ',
    all: 'Բոլոր աշխատանքները',
  },
  band: {
    title: 'Ունե՞ք նախագծի գաղափար։',
    text: 'Պատմեք մեզ դրա մասին․ Ռուբենը կպատասխանի անձամբ։',
    restaurant: 'Ռեստորան',
    art: 'Արվեստի գործ',
    tiles: 'Սալիկներ',
  },
  restaurants: {
    makeSub: '06 տեսակ · ընտրեք և պատվիրեք',
    order: 'Պատվիրել',
    oursTitle: 'Մեր ռեստորանները',
    oursSub: 'Նախագծեր, որոնց համար Ռուբենը ստեղծել է սպասք',
    keepTitle: 'Շարունակեք դիտել…',
    keepSub: 'Մյուս ուղղությունները',
    forYou: 'Ձեր ռեստորանի համար',
    title: 'Սպասք՝ ստեղծված ձեր մենյուի համար։',
    text: 'Կերամիկական հավաքածու՝ ստեղծված ձեր խոհանոցի, սրահի և սպասարկման շուրջ՝ առաջին էսքիզից մինչև կրկնակի պատվեր։',
    cta: 'Պատվիրել անհատական հավաքածու',
    cta2: 'Քննարկել ռեստորանի նախագիծը',
    makeTitle: 'Ինչ ենք պատրաստում',
    make: ['Ափսեներ', 'Թասեր', 'Բաժակներ և գավաթներ', 'Մատուցման ափսեներ', 'Հատուկ սպասք', 'Անհատական ձևեր և չափեր'],
    customTitle: 'Ինչ կարող եք ընտրել',
    custom: ['Ձև և չափ', 'Ջնարակի և գույնի մշակում', 'Մակերես և եզր', 'Ձեր նշանը հատակին', 'Հավաքածուի կազմ'],
    serviceTitle: 'Ստեղծված սպասարկման համար',
    service: 'Հարցրեք այն մասին, ինչը կարևոր է խոհանոցում՝ դարսվելը, աման լվացող մեքենան, եզրի ամրությունը, սննդի համար անվտանգ ջնարակները։',
    projectsTitle: 'Նախագծեր',
    projectsEmpty: 'Նախագծերը նկարահանվում են։ Օրինակների համար գրեք մեզ։',
    stepsTitle: 'Ինչպես ենք աշխատում',
    steps: ['Առաջադրանք', 'Նմուշներ', 'Փորձնական հավաքածու', 'Հաստատում', 'Արտադրություն', 'Առաքում և կրկնակի պատվերներ'],
  },
  art: {
    worksBand: 'Աշխատանքներ',
    title: 'Կավ, կրակ և անհայտը։',
    text: 'Քանդակային անոթներ և եզակի աշխատանքներ՝ պատրաստված բրուտի անիվի վրա, ապա ձեռքով կտրված, ծալված և ծակոտկենված։',
    cta: 'Պատվիրել աշխատանք',
    commissionTitle: 'Աշխատանք՝ ձեր տարածքի համար։',
    commissionText: 'Սկսեք գոյություն ունեցող աշխատանքից կամ մաքուր էջից։',
    year: 'Տարի',
    material: 'Նյութ',
    dimensions: 'Չափեր',
    collection: 'Հավաքածու',
    available: 'Առկա է խանութում',
    similar: 'Պատվիրել նմանատիպ աշխատանք',
    all: 'Բոլորը',
    more: 'Այլ աշխատանքներ',
    startFrom: 'Սկսել առկա աշխատանքից',
    empty: 'Նոր աշխատանքները շուտով կլինեն։',
    cats: {
      sculptural: 'Քանդակային',
      vases: 'Ծաղկամաններ',
      objects: 'Դեկորատիվ առարկաներ',
      interior: 'Ինտերիերի առարկաներ',
      experimental: 'Փորձարարական',
      limited: 'Սահմանափակ հավաքածուներ',
    },
  },
  tiles: {
    title: 'Ձեռագործ մակերեսներ երկարակյաց տարածքների համար։',
    text: 'Անհատական կերամիկական սալիկներ ճարտարապետների, դիզայներների և նրանց ստեղծած տարածքների համար՝ ցանկացած ձևի, ջնարակի կամ նախշի։',
    cta: 'Պատվիրել սալիկներ',
    cta2: 'Սկսել սալիկների նախագիծ',
    forTitle: 'Ում համար',
    for: ['Ճարտարապետներ', 'Ինտերիերի դիզայներներ', 'Ռեստորաններ և հյուրանոցներ', 'Բնակելի տներ', 'Առևտրային տարածքներ'],
    customTitle: 'Անհատական մշակում',
    custom: ['Չափեր', 'Ձևեր', 'Նախշեր', 'Ջնարակի տարբերակներ', 'Ֆակտուրաներ', 'Մշակում զրոյից'],
    stepsTitle: 'Ինչպես ենք աշխատում',
    steps: ['Առաջադրանք', 'Նմուշների տուփ', 'Փորձնական վահանակ', 'Արտադրություն', 'Առաքում'],
    projectsTitle: 'Նախագծեր',
    projectsEmpty: 'Օբյեկտները նկարահանվում են։ Օրինակների համար գրեք մեզ։',
  },
  project: {
    partner: 'Ռեստորան-գործընկեր',
    viewWorks: 'Դիտել աշխատանքները',
    and: 'և',
    served: 'Կերամիկական սպասք՝ ստեղծված ռեստորանի խոհանոցի, սրահի և սպասարկման համար։',
    glance: 'Ռեստորանը մի հայացքով',
    worksTitle: 'Աշխատանքներ ռեստորանի համար',
    worksSub: '{n} աշխատանք · սպասք և մատուցման առարկաներ',
    cardText: 'Ձեռքով պատրաստված Ruben Pap արվեստանոցում, Երևան։',
    orderSimilar: 'Պատվիրել նմանատիպը',
    howWorked: 'Ինչպես ենք աշխատել',
    similarTitle: 'Պատվիրել նմանատիպ հավաքածու',
    similarText: 'Պատմեք ձեր մենյուի և սրահի մասին․ Ռուբենը կպատասխանի անձամբ։',
    all: 'Բոլոր ռեստորանները',
    others: 'Այլ ռեստորաններ, որոնց հետ աշխատել է Ռուբենը',
    closed: 'Փակ է',
    concept: 'Գաղափար',
    collection: 'Հավաքածու',
    materials: 'Նյութեր և ջնարակներ',
    tile: 'Սալիկ',
    pattern: 'Նախշ',
    start: 'Սկսել ձեր նախագիծը',
  },
  shop: {
    title: 'Առկա է հիմա։',
    text: 'Պատրաստված արվեստանոցում և պատրաստ առաքման։ Եզակի աշխատանքը վաճառվելուց հետո այլևս չի կրկնվի։',
    all: 'Բոլորը',
    cats: {
      cups: 'Բաժակներ',
      mugs: 'Գավաթներ',
      plates: 'Ափսեներ',
      bowls: 'Թասեր',
      vases: 'Ծաղկամաններ',
      decor: 'Դեկոր',
      limited: 'Սահմանափակ թողարկումներ',
      unique: 'Եզակի աշխատանքներ',
    },
    empty: 'Այստեղ հիմա ոչինչ չկա․ նոր աշխատանքները շուտով դուրս կգան վառարանից։',
    customTitle: 'Ուզո՞ւմ եք մի բան՝ պատրաստված հատուկ ձեզ համար։',
    customText: 'Նկարագրեք այն, ավելացրեք մի քանի օրինակ լուսանկար, և Ռուբենը կպատրաստի։',
    customCta: 'Պատվիրել անհատական աշխատանք',
    variant: 'Դուր է գալիս, բայց ուզում եք այլ չափ կամ ջնարակ։',
    onRequest: 'Գինը՝ ըստ հարցման',
    unique: 'Եզակի',
    soldOut: 'Վաճառված է',
    add: 'Ավելացնել զամբյուղ',
    added: 'Զամբյուղում է․ դիտել',
    ask: 'Հարցնել այս աշխատանքի մասին',
    handmade: 'Ձեռքով պատրաստված և ջնարակված Երևանում։ Ձևի և ջնարակի փոքր տարբերությունները վարպետի ձեռագիրն են, ոչ թե թերություն։',
    material: 'Նյութ',
    glaze: 'Ջնարակ',
    dimensions: 'Չափեր',
    care: 'Խնամք',
    story: 'Աշխատանքի մասին',
  },
  cart: {
    title: 'Զամբյուղ',
    empty: 'Այստեղ դեռ ոչինչ չկա։ Բայց վառարանը միշտ լի է։',
    qty: 'Քանակ',
    remove: 'Հեռացնել',
    total: 'Ընդամենը',
    send: 'Ուղարկել պատվերը էլ. փոստով',
    note: 'Առցանց վճարումը շուտով։ Ուղարկեք պատվերը, և մենք կհաստատենք առկայությունն ու առաքումը։',
    back: 'Շարունակել գնումները',
    subject: 'Պատվեր կայքից',
  },
  form: {
    title: 'Սկսել նախագիծ',
    text: 'Պատմեք, թե ինչ եք ծրագրում։ Պարտադիր են միայն *-ով նշված դաշտերը։',
    type: 'Նախագծի տեսակ *',
    types: { restaurant: 'Ռեստորանային հավաքածու', art: 'Արվեստի գործ', tiles: 'Սալիկներ', custom: 'Անհատական պատվեր' },
    ref: 'Հղում',
    venue: 'Հաստատության անվանում',
    city: 'Քաղաք',
    pieces: 'Անհրաժեշտ իրեր',
    piecesList: { plates: 'Ափսեներ', bowls: 'Թասեր', cups: 'Բաժակներ և գավաթներ', serving: 'Մատուցման ափսեներ', specialty: 'Հատուկ սպասք' },
    quantity: 'Քանակ',
    kind: 'Աշխատանքի տեսակ',
    kinds: { sculpture: 'Քանդակ', vase: 'Ծաղկաման', object: 'Առարկա', installation: 'Ինստալյացիա' },
    size: 'Մոտավոր չափ (սմ)',
    placement: 'Որտե՞ղ է այն լինելու։',
    role: 'Ձեր դերը',
    roles: { architect: 'Ճարտարապետ', designer: 'Ինտերիերի դիզայներ', owner: 'Սեփականատեր', contractor: 'Կապալառու' },
    area: 'Մակերես (մ²)',
    application: 'Կիրառում',
    applications: { wall: 'Պատ', floor: 'Հատակ', backsplash: 'Խոհանոցի պատ', facade: 'Ճակատ', wet: 'Խոնավ գոտի' },
    item: 'Ի՞նչ պատրաստենք։',
    brief: 'Նկարագրեք ձեր նախագիծը *',
    budget: 'Բյուջե',
    budgets: ['Դեռ չգիտեմ', 'Մինչև $500', '$500 – 2,000', '$2,000 – 10,000', 'Ավելի քան $10,000'],
    deadline: 'Ժամկետ',
    files: 'Օրինակ նկարներ կամ գծագրեր',
    filesHint: 'Մինչև 10 ֆայլ, ընդհանուր՝ մինչև 4 ՄԲ։',
    tooBig: 'Ֆայլերի ընդհանուր չափը գերազանցում է 4 ՄԲ-ը։',
    you: 'Ձեր մասին',
    name: 'Անուն *',
    email: 'Էլ. փոստ',
    phone: 'Հեռախոս / WhatsApp',
    contactHint: 'Պարտադիր է էլ. փոստը կամ հեռախոսը։',
    channel: 'Կապի նախընտրելի միջոց',
    channels: ['Էլ. փոստ', 'WhatsApp', 'Telegram', 'Viber', 'Զանգ'],
    send: 'Ուղարկել',
    sending: 'Ուղարկվում է…',
    sent: 'Շնորհակալություն։ Ձեր հայտը Ռուբենի մոտ է, նա կպատասխանի անձամբ։',
    failed: 'Չհաջողվեց ուղարկել ձևը առցանց։ Ուղարկեք նույն հայտը էլ. փոստով՝',
    mail: 'Բացել էլ. փոստը',
  },
  about: {
    label: 'Արվեստագետի մասին',
    name: 'Ռուբեն Պապ',
    p1: 'Ռուբենը կերամիկայով սկսել է զբաղվել 22 տարեկանում․ աշխատել է երևանյան արվեստանոցներից մեկում և մեկ տասնամյակ փորձարկումներ արել ձևի, կավի ու ջնարակի հետ։',
    p2: '2012 թվականին նա բացել է սեփական արվեստանոցը։ Նրա ստեղծագործությունն ազատորեն շարժվում է արվեստի, դիզայնի և կենցաղային իրերի միջև՝ համատեղելով բրուտի անիվի ավանդական աշխատանքը կտրելու և ձևափոխելու հնարքների հետ, որոնք յուրաքանչյուր իրի տալիս են գծային, կենդանի կառուցվածք։',
    p3: 'Տաք շագանակագույն կավի վրա շերտերով դրված ջնարակները նրա ձեռագիրն են՝ խոր փիրուզագույնից մինչև նորագույն աշխատանքների բրոնզե մակերեսները։',
    quote: '«Երբ աշխատում եմ որևէ իրի վրա, երբեք չգիտեմ, թե ինչ է լինելու»։',
    f1: 'Տարեկանում սկսեց',
    f2: 'Արվեստանոցի հիմնադրում',
    alt: 'Ռուբեն Պապն իր արվեստանոցում՝ աշխատանքի պահին',
  },
  contact: {
    title: 'Գրեք մեզ։',
    email: 'Էլ. փոստ',
    phone: 'Հեռախոս',
    studio: 'Արվեստանոց',
    follow: 'Հետևեք',
    address: 'Կոմիտասի պող. 49/3, 14, Երևան, Հայաստան',
    visits: 'Այց արվեստանոց՝ նախնական պայմանավորվածությամբ',
    map: 'Քարտեզ',
  },
  footer: {
    contact: 'Կապ',
    studio: 'Արվեստանոց',
    social: 'Սոցցանցեր',
    tagline: 'Ձեռքով · Կավ · Կրակ',
  },
  notFound: { title: 'Այս էջը ճաքեց վառարանում։', back: 'Գլխավոր էջ' },
}

const ru: Overrides = {
  meta: {
    description:
      'Керамист Рубен Пап создаёт посуду для ресторанов, предметы для коллекционеров и плитку для архитектуры — вручную, в Ереване, с 2012 года.',
  },
  ui: { skip: 'Перейти к содержанию', menu: 'Меню', main: 'Основное', language: 'Язык', cart: 'Корзина', theme: 'Светлая / тёмная', back: 'Главная', prev: 'Назад', next: 'Вперёд' },
  brand: { sub: 'Керамика · Ереван' },
  nav: {
    restaurants: 'Рестораны и посуда',
    art: 'Авторское искусство',
    tiles: 'Декор и плитка',
    shop: 'Магазин',
    about: 'О мастере',
    contact: 'Контакты',
  },
  home: {
    titleThin: 'Сделано руками.',
    titleBold: 'Сделано с характером.',
    meta1: 'Керамика — ручная работа, на заказ',
    meta2: 'С 2012 · Ереван',
    worldsTitle: 'Четыре мира',
    worldsCount: '4 направления',
    commissionLink: 'Заказать',
    worksTitle: 'Избранные работы',
    partners: 'Рестораны-партнёры',
    studio: 'Из мастерской',
    title: 'Сделано руками. Сделано с характером.',
    text: 'Керамист Рубен Пап создаёт посуду для ресторанов, предметы для коллекционеров и плитку для архитектуры — в своей ереванской студии с 2012 года.',
    alt: 'Ажурная чаша из каменной массы на фоне окна студии',
    restaurants: 'Авторская керамическая посуда для ресторанов и отелей.',
    art: 'Образная керамика и коллекционные работы.',
    tiles: 'Рукотворные поверхности и декор для интерьеров и архитектурных пространств.',
    shop: 'Готовые работы из студии.',
    explore: 'Смотреть',
    shopNow: 'В магазин',
    selected: 'Избранные предметы',
    all: 'Все работы',
  },
  band: {
    title: 'Есть идея проекта?',
    text: 'Расскажите о ней — Рубен ответит лично.',
    restaurant: 'Ресторан',
    art: 'Арт-объект',
    tiles: 'Плитка',
  },
  restaurants: {
    makeSub: '06 видов · выберите и закажите',
    order: 'Заказать',
    oursTitle: 'Наши рестораны',
    oursSub: 'Проекты, для которых Рубен создал посуду',
    keepTitle: 'Смотрите также…',
    keepSub: 'Другие направления',
    forYou: 'Для вашего ресторана',
    title: 'Посуда, созданная для вашего меню.',
    text: 'Керамическая коллекция под вашу кухню, ваш зал и ваш сервис — от первого эскиза до дозаказа.',
    cta: 'Заказать коллекцию',
    cta2: 'Обсудить проект ресторана',
    makeTitle: 'Что мы делаем',
    make: ['Тарелки', 'Чаши', 'Чашки и кружки', 'Сервировочные блюда', 'Особая посуда', 'Любые формы и размеры'],
    customTitle: 'Что можно настроить',
    custom: ['Форма и размер', 'Разработка глазури и цвета', 'Поверхность и край', 'Ваш знак на донце', 'Состав сета'],
    serviceTitle: 'Для работы в зале',
    service: 'Спросите о том, что важно на кухне: штабелирование, посудомоечная машина, прочность края, пищевые глазури.',
    projectsTitle: 'Проекты',
    projectsEmpty: 'Кейсы сейчас фотографируются. Напишите нам, чтобы получить примеры.',
    stepsTitle: 'Как это работает',
    steps: ['Бриф', 'Образцы', 'Пробный сет', 'Утверждение', 'Производство', 'Доставка и дозаказы'],
  },
  art: {
    worksBand: 'Работы',
    title: 'Глина, огонь и неизвестность.',
    text: 'Скульптурные сосуды и уникальные работы — сделанные на гончарном круге, затем разрезанные, сложенные и прорезанные вручную.',
    cta: 'Заказать работу',
    commissionTitle: 'Работа для вашего пространства.',
    commissionText: 'Начните с существующей работы или с чистого листа.',
    year: 'Год',
    material: 'Материал',
    dimensions: 'Размеры',
    collection: 'Коллекция',
    available: 'Есть в магазине',
    similar: 'Заказать похожую работу',
    all: 'Все',
    more: 'Другие работы',
    startFrom: 'Начать с существующей работы',
    empty: 'Новые работы скоро появятся.',
    cats: {
      sculptural: 'Скульптура',
      vases: 'Вазы',
      objects: 'Декоративные предметы',
      interior: 'Предметы интерьера',
      experimental: 'Эксперименты',
      limited: 'Лимитированные коллекции',
    },
  },
  tiles: {
    title: 'Поверхности ручной работы для долговечных пространств.',
    text: 'Авторская керамическая плитка для архитекторов, дизайнеров и пространств, которые они создают, — любой формы, глазури и рисунка.',
    cta: 'Запросить плитку',
    cta2: 'Начать проект с плиткой',
    forTitle: 'Для кого',
    for: ['Архитекторы', 'Дизайнеры интерьеров', 'Рестораны и отели', 'Частные дома', 'Коммерческие пространства'],
    customTitle: 'Индивидуальная разработка',
    custom: ['Размеры', 'Формы', 'Рисунки', 'Варианты глазури', 'Фактуры', 'Разработка с нуля'],
    stepsTitle: 'Как это работает',
    steps: ['Бриф', 'Набор образцов', 'Пробная панель', 'Производство', 'Доставка'],
    projectsTitle: 'Проекты',
    projectsEmpty: 'Объекты сейчас фотографируются. Напишите нам, чтобы получить примеры.',
  },
  project: {
    partner: 'Ресторан-партнёр',
    viewWorks: 'Смотреть работы',
    and: 'и',
    served: 'Керамическая посуда, созданная для кухни, зала и сервиса ресторана.',
    glance: 'Ресторан в двух словах',
    worksTitle: 'Работы для ресторана',
    worksSub: '{n} работы · посуда и сервировка',
    cardText: 'Сделано вручную в мастерской Ruben Pap, Ереван.',
    orderSimilar: 'Заказать похожее',
    howWorked: 'Как мы работали',
    similarTitle: 'Заказать похожую коллекцию',
    similarText: 'Расскажите о вашем меню и зале — Рубен ответит лично.',
    all: 'Все рестораны',
    others: 'Другие рестораны, с которыми работал Рубен',
    closed: 'Закрыт',
    concept: 'Концепция',
    collection: 'Коллекция',
    materials: 'Материалы и глазури',
    tile: 'Плитка',
    pattern: 'Раскладка',
    start: 'Начать свой проект',
  },
  shop: {
    title: 'В наличии.',
    text: 'Сделано в студии и готово к отправке. Когда уникальная вещь продана, её больше нет.',
    all: 'Все',
    cats: {
      cups: 'Чашки',
      mugs: 'Кружки',
      plates: 'Тарелки',
      bowls: 'Чаши',
      vases: 'Вазы',
      decor: 'Декор',
      limited: 'Лимитированные серии',
      unique: 'Уникальные',
    },
    empty: 'Сейчас здесь пусто — новые работы скоро выйдут из печи.',
    customTitle: 'Хотите вещь, сделанную специально для вас?',
    customText: 'Опишите её и добавьте пару фото-референсов — Рубен её сделает.',
    customCta: 'Заказать индивидуальную работу',
    variant: 'Нравится, но нужен другой размер или глазурь?',
    onRequest: 'Цена по запросу',
    unique: 'В единственном экземпляре',
    soldOut: 'Продано',
    add: 'В корзину',
    added: 'В корзине — открыть',
    ask: 'Спросить об этой работе',
    handmade: 'Сформовано и покрыто глазурью вручную в Ереване. Небольшие различия в форме и глазури — почерк мастера, а не дефект.',
    material: 'Материал',
    glaze: 'Глазурь',
    dimensions: 'Размеры',
    care: 'Уход',
    story: 'О работе',
  },
  cart: {
    title: 'Корзина',
    empty: 'Здесь пока пусто. Зато печь всегда полна.',
    qty: 'Количество',
    remove: 'Удалить',
    total: 'Итого',
    send: 'Отправить заказ по почте',
    note: 'Онлайн-оплата скоро появится. Отправьте заказ — мы подтвердим наличие и доставку.',
    back: 'Продолжить покупки',
    subject: 'Заказ с сайта',
  },
  form: {
    title: 'Начать проект',
    text: 'Расскажите, что вы задумали. Обязательны только поля со *.',
    type: 'Тип проекта *',
    types: { restaurant: 'Коллекция для ресторана', art: 'Арт-объект', tiles: 'Плитка', custom: 'Индивидуальный заказ' },
    ref: 'Референс',
    venue: 'Название заведения',
    city: 'Город',
    pieces: 'Что нужно',
    piecesList: { plates: 'Тарелки', bowls: 'Чаши', cups: 'Чашки и кружки', serving: 'Сервировочные блюда', specialty: 'Особая посуда' },
    quantity: 'Количество',
    kind: 'Тип работы',
    kinds: { sculpture: 'Скульптура', vase: 'Ваза', object: 'Предмет', installation: 'Инсталляция' },
    size: 'Примерный размер (см)',
    placement: 'Где она будет жить?',
    role: 'Ваша роль',
    roles: { architect: 'Архитектор', designer: 'Дизайнер интерьеров', owner: 'Владелец', contractor: 'Подрядчик' },
    area: 'Площадь (м²)',
    application: 'Применение',
    applications: { wall: 'Стена', floor: 'Пол', backsplash: 'Фартук', facade: 'Фасад', wet: 'Влажная зона' },
    item: 'Что нам сделать?',
    brief: 'Опишите проект *',
    budget: 'Бюджет',
    budgets: ['Пока не знаю', 'До $500', '$500 – 2 000', '$2 000 – 10 000', 'Более $10 000'],
    deadline: 'Срок',
    files: 'Референсы или чертежи',
    filesHint: 'До 10 файлов, всего до 4 МБ.',
    tooBig: 'Файлы в сумме больше 4 МБ.',
    you: 'О вас',
    name: 'Имя *',
    email: 'Эл. почта',
    phone: 'Телефон / WhatsApp',
    contactHint: 'Нужна почта или телефон.',
    channel: 'Удобный способ связи',
    channels: ['Эл. почта', 'WhatsApp', 'Telegram', 'Viber', 'Звонок'],
    send: 'Отправить',
    sending: 'Отправка…',
    sent: 'Спасибо — ваш бриф у Рубена. Он ответит лично.',
    failed: 'Не удалось отправить форму онлайн. Отправьте тот же бриф по почте:',
    mail: 'Открыть почту',
  },
  about: {
    label: 'О мастере',
    name: 'Рубен Пап',
    p1: 'Рубен начал заниматься керамикой в 22 года: работал в одной из ереванских студий и целое десятилетие экспериментировал с формой, глиной и глазурью.',
    p2: 'В 2012 году он открыл собственную студию. Его практика свободно перемещается между искусством, дизайном и функциональной посудой, соединяя традиционную работу на гончарном круге с надрезами и деформацией, которые придают каждому предмету линейную, живую структуру.',
    p3: 'Многослойные глазури поверх тёплой коричневой глины — его фирменный почерк: от глубокой бирюзы до бронзовых поверхностей новых работ.',
    quote: '«Когда я работаю над вещью, я никогда не знаю, что из этого выйдет».',
    f1: 'Года — начало пути',
    f2: 'Основана студия',
    alt: 'Рубен Пап за работой в своей студии',
  },
  contact: {
    title: 'Напишите нам.',
    email: 'Эл. почта',
    phone: 'Телефон',
    studio: 'Студия',
    follow: 'Соцсети',
    address: 'пр. Комитаса, 49/3, 14, Ереван, Армения',
    visits: 'Посещение студии по записи',
    map: 'Карта',
  },
  footer: {
    contact: 'Контакты',
    studio: 'Мастерская',
    social: 'Соцсети',
    tagline: 'Руками · Глина · Огонь',
  },
  notFound: { title: 'Эта страница треснула в печи.', back: 'На главную' },
}

const de: Overrides = {
  meta: {
    description:
      'Der Keramiker Ruben Pap fertigt Geschirr für Restaurants, Objekte für Sammler und Fliesen für die Architektur — von Hand, in Jerewan, seit 2012.',
  },
  ui: { skip: 'Zum Inhalt springen', menu: 'Menü', main: 'Hauptmenü', language: 'Sprache', cart: 'Warenkorb', theme: 'Hell / dunkel', back: 'Startseite', prev: 'Zurück', next: 'Weiter' },
  brand: { sub: 'Keramik · Jerewan' },
  nav: {
    restaurants: 'Restaurants & Geschirr',
    art: 'Kunstwerke',
    tiles: 'Dekor & Fliesen',
    shop: 'Shop',
    about: 'Über Ruben',
    contact: 'Kontakt',
  },
  home: {
    titleThin: 'Von Hand gemacht.',
    titleBold: 'Mit Charakter.',
    meta1: 'Keramik — handgemacht, auf Bestellung',
    meta2: 'Seit 2012 · Jerewan',
    worldsTitle: 'Vier Welten',
    worldsCount: '4 Bereiche',
    commissionLink: 'Anfragen',
    worksTitle: 'Ausgewählte Arbeiten',
    partners: 'Partnerrestaurants',
    studio: 'Aus dem Atelier',
    title: 'Von Hand gemacht. Mit Charakter.',
    text: 'Der Keramiker Ruben Pap fertigt Geschirr für Restaurants, Objekte für Sammler und Fliesen für die Architektur — in seinem Atelier in Jerewan seit 2012.',
    alt: 'Durchbrochene Steinzeugschale vor einem Atelierfenster',
    restaurants: 'Maßgefertigtes Keramikgeschirr für die Gastronomie.',
    art: 'Fantasievolle Keramikobjekte und Sammlerstücke.',
    tiles: 'Handgemachte Oberflächen und Dekor für Innenräume und Architektur.',
    shop: 'Verfügbare Stücke aus dem Atelier.',
    explore: 'Entdecken',
    shopNow: 'Zum Shop',
    selected: 'Ausgewählte Objekte',
    all: 'Alle Arbeiten',
  },
  band: {
    title: 'Sie haben ein Projekt im Kopf?',
    text: 'Erzählen Sie uns davon — Ruben antwortet persönlich.',
    restaurant: 'Restaurant',
    art: 'Kunstobjekt',
    tiles: 'Fliesen',
  },
  restaurants: {
    makeSub: '06 Arten · auswählen und bestellen',
    order: 'Bestellen',
    oursTitle: 'Unsere Restaurants',
    oursSub: 'Projekte, für die Ruben Geschirr gefertigt hat',
    keepTitle: 'Weiter entdecken…',
    keepSub: 'Die anderen Bereiche',
    forYou: 'Für Ihr Restaurant',
    title: 'Geschirr, gemacht für Ihre Karte.',
    text: 'Eine Keramikkollektion rund um Ihre Küche, Ihren Raum und Ihren Service — vom ersten Entwurf bis zur Nachbestellung.',
    cta: 'Eigene Kollektion bestellen',
    cta2: 'Ihr Restaurantprojekt besprechen',
    makeTitle: 'Was wir fertigen',
    make: ['Teller', 'Schalen', 'Tassen & Becher', 'Servierplatten', 'Spezialgeschirr', 'Eigene Formen & Größen'],
    customTitle: 'Was Sie anpassen können',
    custom: ['Form & Größe', 'Glasur- und Farbentwicklung', 'Oberfläche & Rand', 'Ihr Zeichen auf der Unterseite', 'Zusammenstellung des Sets'],
    serviceTitle: 'Gemacht für den Service',
    service: 'Fragen Sie nach dem, was in der Küche zählt: Stapelbarkeit, Spülmaschine, Randfestigkeit, lebensmittelechte Glasuren.',
    projectsTitle: 'Projekte',
    projectsEmpty: 'Die Fallstudien werden gerade fotografiert. Schreiben Sie uns für Referenzen.',
    stepsTitle: 'So funktioniert es',
    steps: ['Briefing', 'Muster', 'Prototyp-Set', 'Freigabe', 'Produktion', 'Lieferung & Nachbestellung'],
  },
  art: {
    worksBand: 'Arbeiten',
    title: 'Ton, Feuer & das Unbekannte.',
    text: 'Skulpturale Gefäße und Unikate — auf der Scheibe gedreht, dann von Hand geschnitten, gefaltet und durchbrochen.',
    cta: 'Ein Stück in Auftrag geben',
    commissionTitle: 'Ein Stück für Ihren Raum.',
    commissionText: 'Beginnen Sie mit einer bestehenden Arbeit oder mit einem leeren Blatt.',
    year: 'Jahr',
    material: 'Material',
    dimensions: 'Maße',
    collection: 'Kollektion',
    available: 'Im Shop erhältlich',
    similar: 'Ein ähnliches Stück in Auftrag geben',
    all: 'Alle',
    more: 'Weitere Arbeiten',
    startFrom: 'Mit einer bestehenden Arbeit beginnen',
    empty: 'Neue Arbeiten sind unterwegs.',
    cats: {
      sculptural: 'Skulptural',
      vases: 'Vasen',
      objects: 'Dekorative Objekte',
      interior: 'Interieurobjekte',
      experimental: 'Experimentell',
      limited: 'Limitierte Kollektionen',
    },
  },
  tiles: {
    title: 'Handgemachte Oberflächen für Räume, die bleiben.',
    text: 'Maßgefertigte Keramikfliesen für Architekten, Designer und die Räume, die sie bauen — in jeder Form, Glasur und jedem Muster.',
    cta: 'Fliesen anfragen',
    cta2: 'Ein Fliesenprojekt starten',
    forTitle: 'Gemacht für',
    for: ['Architekten', 'Innenarchitekten', 'Restaurants & Hotels', 'Wohnräume', 'Gewerberäume'],
    customTitle: 'Individuelle Entwicklung',
    custom: ['Maße', 'Formen', 'Muster', 'Glasurvarianten', 'Texturen', 'Entwicklung nach Maß'],
    stepsTitle: 'So funktioniert es',
    steps: ['Briefing', 'Musterbox', 'Musterfläche', 'Produktion', 'Lieferung'],
    projectsTitle: 'Projekte',
    projectsEmpty: 'Die Installationen werden gerade fotografiert. Schreiben Sie uns für Referenzen.',
  },
  project: {
    partner: 'Partnerrestaurant',
    viewWorks: 'Arbeiten ansehen',
    and: 'und',
    served: 'Keramikgeschirr für Küche, Gastraum und Service des Restaurants.',
    glance: 'Das Restaurant auf einen Blick',
    worksTitle: 'Arbeiten für das Restaurant',
    worksSub: '{n} Arbeiten · Geschirr und Servierstücke',
    cardText: 'Handgefertigt im Atelier Ruben Pap, Jerewan.',
    orderSimilar: 'Ähnliches anfragen',
    howWorked: 'So haben wir gearbeitet',
    similarTitle: 'Ähnliche Kollektion anfragen',
    similarText: 'Erzählen Sie von Ihrer Karte und Ihrem Raum — Ruben antwortet persönlich.',
    all: 'Alle Restaurants',
    others: 'Weitere Restaurants, mit denen Ruben gearbeitet hat',
    closed: 'Geschlossen',
    concept: 'Konzept',
    collection: 'Kollektion',
    materials: 'Materialien & Glasuren',
    tile: 'Fliese',
    pattern: 'Muster',
    start: 'Ihr Projekt starten',
  },
  shop: {
    title: 'Jetzt verfügbar.',
    text: 'Im Atelier gefertigt, bereit zum Versand. Ist ein Unikat verkauft, ist es weg.',
    all: 'Alle',
    cats: {
      cups: 'Tassen',
      mugs: 'Becher',
      plates: 'Teller',
      bowls: 'Schalen',
      vases: 'Vasen',
      decor: 'Dekor',
      limited: 'Limitierte Editionen',
      unique: 'Unikate',
    },
    empty: 'Gerade ist hier nichts — neue Stücke kommen bald aus dem Ofen.',
    customTitle: 'Etwas, das eigens für Sie gefertigt wird?',
    customText: 'Beschreiben Sie es, fügen Sie ein paar Referenzfotos hinzu — Ruben fertigt es.',
    customCta: 'Ein Einzelstück anfragen',
    variant: 'Gefällt Ihnen, aber in anderer Größe oder Glasur?',
    onRequest: 'Preis auf Anfrage',
    unique: 'Unikat',
    soldOut: 'Verkauft',
    add: 'In den Warenkorb',
    added: 'Im Warenkorb — ansehen',
    ask: 'Nach diesem Stück fragen',
    handmade: 'Von Hand gedreht und glasiert in Jerewan. Kleine Unterschiede in Form und Glasur sind die Handschrift des Künstlers, keine Fehler.',
    material: 'Material',
    glaze: 'Glasur',
    dimensions: 'Maße',
    care: 'Pflege',
    story: 'Über die Arbeit',
  },
  cart: {
    title: 'Warenkorb',
    empty: 'Noch nichts hier. Der Ofen ist aber immer voll.',
    qty: 'Menge',
    remove: 'Entfernen',
    total: 'Summe',
    send: 'Bestellung per E-Mail senden',
    note: 'Online-Zahlung folgt in Kürze. Senden Sie die Bestellung — wir bestätigen Verfügbarkeit und Versand.',
    back: 'Weiter einkaufen',
    subject: 'Bestellung über die Website',
  },
  form: {
    title: 'Ein Projekt starten',
    text: 'Erzählen Sie uns, was Sie planen. Pflichtfelder sind mit * markiert.',
    type: 'Projektart *',
    types: { restaurant: 'Restaurantkollektion', art: 'Kunstobjekt', tiles: 'Fliesen', custom: 'Einzelstück' },
    ref: 'Referenz',
    venue: 'Name des Lokals',
    city: 'Stadt',
    pieces: 'Benötigte Stücke',
    piecesList: { plates: 'Teller', bowls: 'Schalen', cups: 'Tassen & Becher', serving: 'Servierplatten', specialty: 'Spezialgeschirr' },
    quantity: 'Anzahl',
    kind: 'Art der Arbeit',
    kinds: { sculpture: 'Skulptur', vase: 'Vase', object: 'Objekt', installation: 'Installation' },
    size: 'Ungefähre Größe (cm)',
    placement: 'Wo wird es stehen?',
    role: 'Ihre Rolle',
    roles: { architect: 'Architekt:in', designer: 'Innenarchitekt:in', owner: 'Eigentümer:in', contractor: 'Bauunternehmen' },
    area: 'Fläche (m²)',
    application: 'Einsatz',
    applications: { wall: 'Wand', floor: 'Boden', backsplash: 'Küchenrückwand', facade: 'Fassade', wet: 'Nassbereich' },
    item: 'Was sollen wir fertigen?',
    brief: 'Beschreiben Sie Ihr Projekt *',
    budget: 'Budget',
    budgets: ['Noch unklar', 'Unter 500 $', '500 – 2.000 $', '2.000 – 10.000 $', 'Über 10.000 $'],
    deadline: 'Termin',
    files: 'Referenzbilder oder Zeichnungen',
    filesHint: 'Bis zu 10 Dateien, insgesamt 4 MB.',
    tooBig: 'Die Dateien sind zusammen größer als 4 MB.',
    you: 'Über Sie',
    name: 'Name *',
    email: 'E-Mail',
    phone: 'Telefon / WhatsApp',
    contactHint: 'E-Mail oder Telefon ist erforderlich.',
    channel: 'Bevorzugter Kanal',
    channels: ['E-Mail', 'WhatsApp', 'Telegram', 'Viber', 'Anruf'],
    send: 'Senden',
    sending: 'Wird gesendet…',
    sent: 'Danke — Ihr Briefing ist bei Ruben. Er antwortet persönlich.',
    failed: 'Das Formular konnte nicht online gesendet werden. Senden Sie dasselbe Briefing per E-Mail:',
    mail: 'E-Mail öffnen',
  },
  about: {
    label: 'Über den Künstler',
    name: 'Ruben Pap',
    p1: 'Ruben begann mit 22 Jahren, Keramik zu lernen. Er arbeitete in einem Atelier in Jerewan und experimentierte ein Jahrzehnt lang mit Form, Ton und Glasur.',
    p2: '2012 eröffnete er sein eigenes Atelier. Seine Arbeit bewegt sich frei zwischen Kunst, Design und Gebrauchskeramik — sie verbindet das traditionelle Drehen auf der Scheibe mit Schneiden und Verformen, das jedem Stück eine lineare, lebendige Struktur verleiht.',
    p3: 'Geschichtete Glasuren auf warmem braunem Ton sind sein Markenzeichen — vom tiefen Türkis bis zu den bronzenen Oberflächen seiner neuesten Arbeiten.',
    quote: '„Wenn ich an einem Stück arbeite, weiß ich nie, was passieren wird.“',
    f1: 'Jahre alt beim Einstieg',
    f2: 'Atelier gegründet',
    alt: 'Ruben Pap bei der Arbeit in seinem Atelier',
  },
  contact: {
    title: 'Sagen Sie Hallo.',
    email: 'E-Mail',
    phone: 'Telefon',
    studio: 'Atelier',
    follow: 'Folgen',
    address: 'Komitas St. 49/3, 14, Jerewan, Armenien',
    visits: 'Atelierbesuche nach Vereinbarung',
    map: 'Karte',
  },
  footer: {
    contact: 'Kontakt',
    studio: 'Atelier',
    social: 'Social Media',
    tagline: 'Hand · Ton · Feuer',
  },
  notFound: { title: 'Diese Seite ist im Ofen gesprungen.', back: 'Zur Startseite' },
}

const overrides: Record<Exclude<Locale, 'en'>, Overrides> = { hy, ru, de }

export const dict = (lang: Locale): Dict =>
  lang === 'en'
    ? en
    : (Object.fromEntries(
        Object.entries(en).map(([k, v]) => [k, { ...v, ...overrides[lang][k as keyof Dict] }]),
      ) as Dict)
